name: Hello # ワークフロー名
on: push #イベントの定義 (on: [push, pull_request])
jobs: #ジョブの定義
  hello: #ジョブID
    runs-on: ubuntu-latest #ランナー(Ubuntuの定義) ≒ ジョブの実行キーがランナー(runs-on)。
    steps:  #ステップの定義 (ステップは段階的に分けることができる。 処理は上から順に実行される.) ※シェルコマンドとアクションの呼び出しがある

     - run: echo "Hello World!" #シェルコマンドの定義
     - users: actions/checkout@v4 #アクションの呼び出し
      with: #入力パラメータを指定できる
        ref: main