name: Secreas
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - run: echo "${{ PASSWORD }}"
      - run: echo "${{ PASSWORD:0:1 }} ${PASSWORD}" # ログマスク挙動確認で使う。 パスワードの先頭1文字を出力
